package com.app.court.global;

public class WebServiceConstants {
    public static final String SERVICE_URL = "";
    public static final String Local_SERVICE_URL = "http://court.stagingic.com/api/";
    public static final String SUCCESS_RESPONSE_CODE = "200";
    public static final String GOOGLE_LAT_LONG_INFO_URL = "http://maps.googleapis.com";

    public static final String LOGIN = "LOGIN";
    public static final String SIGN_UP = "SIGN_UP";
    public static final String GET_PROFILE = "GET_PROFILE";
    public static final String UPDATE_PROFILE = "UPDATE_PROFILE";
    public static final String FORGOT_PASSWORD = "FORGOT_PASSWORD";
    public static final String CODE_VERIFICATION = "CODE_VERIFICATION";
    public static final String SIGNUP_CODE_VERIFICATION = "SIGNUP_CODE_VERIFICATION";
    public static final String RESEND_PASSWORD = "RESEND_PASSWORD";
    public static final String RESEND_CODE = "RESEND_CODE";
    public static final String PUSH_ON_OFF = "PUSH_ON_OFF";
    public static final String LANGUAGE_CHANGE = "LANGUAGE_CHANGE";
    public static final String UPDATE_DEVICE_TOKEN = "UPDATE_DEVICE_TOKEN";
    public static final String CHANGE_PASSWORD = "CHANGE_PASSWORD";
    public static final String GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
    public static final String GET_CMS = "GET_CMS";
    public static final String LOGOUT = "LOGOUT";
    public static final String LANGUAGE = "LANGUAGE";
    public static final String AFFILIATION = "AFFILIATION";
    public static final String EXPERIENCE = "EXPERIENCE";
    public static final String SPECIALIZATION = "SPECIALIZATION";
    public static final String FIND_LAWYERS = "FIND_LAWYERS";
    public static final String MY_CASE = "MY_CASE";
    public static final String MY_CASE_COMMENTS = "MY_CASE_COMMENTS";
    public static final String PAYMENT_DUE = "PAYMENT_DUE";
    public static final String PAYMENT_HISTORY = "PAYMENT_HISTORY";
    public static final String PAY_NOW = "PAY_NOW";
    public static final String MARK_COMPLETE = "MARK_COMPLETE";
    public static final String NEW_COMMENT = "NEW_COMMENT";
    public static final String MESSAGE_THREAD = "MESSAGE_THREAD";
    public static final String CHAT_MESSAGE = "CHAT_MESSAGE";
    public static final String MESSAGE_ADD = "MESSAGE_ADD";
    public static final String CASE_MESSAGE = "CASE_MESSAGE";
    public static final String ALL_LIBRARY = "ALL_LIBRARY";
    public static final String SUBMIT_CASE = "SUBMIT_CASE";
    public static final String SEND_MSG = "SEND_MSG";
    public static final String UPDATEDEVICETOKEN = "UPDATEDEVICETOKEN";
    public static final String MSGPUSH = "MSGPUSH";
    public static final String PUSHONOFF = "PUSHONOFF";
    public static final String CaseDetail = "CaseDetail";
    public static final String RateLawyer = "RateLawyer";
    public static final String WITHDRAWCASE = "WITHDRAWCASE";
}
